logger:
  project: "kaori/AISeed" # replace with your own
  api_key: YOUR API KEY # replace with your own
  tags: ['test UNet']
architect_settings:
  n_filters: 4
  n_layers: 4
  channel: 3
  n_cls: 2
  conv:
    k: 3
    s: 2
    p: 1
  transpose_conv:
    k: 3
    s: 2
    p: 1
dataset_settings:
  name: Lung-CT-Scan
  path: data/CT-scan-dataset
  img_size: 224
training_settings: 
  gpu_ids: [0]
  n_gpu: 1
  loss: ce
  metric: dice
  n_epoch: 100
  n_batch: 64
  num_workers: 0
  optimizer: adam
  lr_scheduler: step
  early_stopping: false
  lr: 0.0001
  lr_step: 10
  lr_decay: 0.8
  momentum: 0.9
  weight_decay: 0.005